### ISSUE TITLE
Keyboard doesn't work on the lock screen after restarting the device

### ISSUE THREAD

**Issue by N1ghttmare** [FossifyOrg/Keyboard#61] opened 2024-07-26 04:31 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Keyboard/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Keyboard/issues) or [closed](https://github.com/FossifyOrg/Keyboard/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Keyboard/discussions) or [closed](https://github.com/FossifyOrg/Keyboard/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Keyboard/blob/main/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 13

### Affected device model

Motorola Moto G54

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1 - Press the power button;

2 - Select the option to restart the smartphone;

3 - On the lock screen, when you try to enter the password, the keyboard crashes completely and disappears constantly, making it impossible to use the smartphone completely and also to restart or turn it off.

### Expected behavior

Enter the password on the lock screen as usual and access the smartphone.

### Actual behavior

The keyboard crashes and disappears constantly, making it impossible to enter the password and restart or turn off the smartphone.

**Comment by Aga-C** [comment] 2024-07-26 05:11
It's a duplicate of https://github.com/FossifyOrg/Keyboard/issues/59.

**Closed by Aga-C** 2024-07-26 05:11 UTC
Labels: bug, needs triage
