### ISSUE TITLE
Keyboard not working on lock screen after phone restart

### ISSUE THREAD

**Issue by CKMz17** [FossifyOrg/Keyboard#90] opened 2024-10-08 13:47 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Keyboard/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Keyboard/issues) or [closed](https://github.com/FossifyOrg/Keyboard/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Keyboard/discussions) or [closed](https://github.com/FossifyOrg/Keyboard/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Keyboard/blob/main/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 14

### Affected device model

Cubot KingKong AX

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

Just restart phone, and keyboard not working on lock screen

### Expected behavior

Well, I think it should work

### Actual behavior

During the unlock screen(after restart) you'll be forced to set the default keyboard of the device, as yours doesn't seem to work in that context: simply as soon as you open the text field it closes instantly, resulting in an unpleasant experience: switching the keyboard in that situation is not very easy; you have to tap several times

### Additional information

I don't know if it's useful, but I'm obviously not using a PIN screen lock but a long alphanumeric password with special characters

**Comment by naveensingh** [comment] 2024-10-08 13:49
Duplicate of https://github.com/FossifyOrg/Keyboard/issues/59

**Closed by naveensingh** 2024-10-08 13:49 UTC
Labels: bug, needs triage

**Comment by CKMz17** [comment] 2024-10-08 14:33
True, sorry, I checked only open issues
