### ISSUE TITLE
Alternate German Layout

### ISSUE THREAD

**Issue by newhinton** [FossifyOrg/Keyboard#105] opened 2024-11-04 19:43 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Keyboard/issues) or [closed](https://github.com/FossifyOrg/Keyboard/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Keyboard/discussions) or [closed](https://github.com/FossifyOrg/Keyboard/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Keyboard/blob/main/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

I would like to have an alternate german keyboard layout that hides the umlauts. 

<img alt="Screenshot_20241104_201655" src="https://github.com/user-attachments/assets/b363449a-ba0d-4159-8cee-6beb972b5eb2" width=180 />

### Why do you want this feature?

This is very similar to the aosp-keyboard that is delivered with most custom roms, and i find it more comfortable. I already implemented this feature and can create a PR if this would be accepted.

**Comment by Aga-C** [comment] 2024-11-04 20:51
It's a duplicate of https://github.com/FossifyOrg/Keyboard/issues/47.

**Closed by Aga-C** 2024-11-04 20:51 UTC
Labels: feature request, needs triage
