### ISSUE TITLE
[Serious bug] Cant open or switch to another keyboard to unlock phone after restart.

### ISSUE THREAD

**Issue by Isakovsky92** [FossifyOrg/Keyboard#60] opened 2024-07-24 16:13 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Keyboard/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Keyboard/issues) or [closed](https://github.com/FossifyOrg/Keyboard/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Keyboard/discussions) or [closed](https://github.com/FossifyOrg/Keyboard/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Keyboard/blob/main/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 13

### Affected device model

Samsung Galaxy Note 20 5G

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

If Fossify keyboard is set as your standard keyboard:
1. Restart phone
2. Type in PIN for SIM card (uses Samsungs pin-keyboard)
3. Phone says you cant use fingerprint after a restart so you have to type in your password.
4. If you have password and not a PIN-code your standard keyboard will try to open.
5. If its Fossify keyboard then it will not open, and if you press the button to change to another keyboard that meny will not open ether. The "choose keyboard menu" will just flicker for parts of a secound with no ability to click on anything.
**6. This means you are stuck here,** if you dont, as in my case, have a OTG-adapter and a physical keyboard to connect to your phone and use this to type in your password.

If you dont have Fossify as your default keyboard its the same if you at the "type in password screen" go in to the "choose keyboard meny" and change to Fossify keyboard. If you dont change everything works as it should.

### Expected behavior

The keyboard should open and also the "choose keyboard menu" should so i am able to type in my password to unlck the phone.

### Actual behavior

As above.

### Screenshots/Screen recordings

No ability to screenshot due to phone in locked mode.

**Comment by Aga-C** [comment] 2024-07-24 16:36
It's a duplicate of https://github.com/FossifyOrg/Keyboard/issues/59.

**Closed** 2024-07-24 16:36 UTC
Labels: bug, needs triage
