### ISSUE TITLE
Opening a full screen video on apps breaks the bottom row of keyboard

### ISSUE THREAD

**Issue by CKMz17** [FossifyOrg/Keyboard#89] opened 2024-10-08 13:02 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Keyboard/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Keyboard/issues) or [closed](https://github.com/FossifyOrg/Keyboard/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Keyboard/discussions) or [closed](https://github.com/FossifyOrg/Keyboard/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Keyboard/blob/main/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 10

### Affected device model

Doogee S68

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

Just open a video with fullscreen in streaming app(like Youtube or others) and then open any text field

### Expected behavior

No changes should apply

### Actual behavior

The last row of the keyboard is covered and unusable after opening a full screen video on any app

### Screenshots/Screen recordings

<img width="208" alt="Screen" src="https://github.com/user-attachments/assets/298a6c10-af7b-452e-be09-761b985225a6">

### Additional information

To fix the keyboard you need to go to reswitch keyboard on your app or android settings

**Comment by naveensingh** [comment] 2024-10-08 13:50
Duplicate of https://github.com/FossifyOrg/Keyboard/issues/69

**Closed by naveensingh** 2024-10-08 13:50 UTC
Labels: bug, needs triage

**Comment by CKMz17** [comment] 2024-10-08 14:32
I had seen that issue, but I think it's different.
On Android 14 I can't reproduce either what I reported or what you linked. And as I wrote, the last line isn't only covered but also unusable (if you tap it doesn't make space or send button)

**Comment by naveensingh** [comment] 2024-10-08 15:04
Both issues seem to have the same underlying cause, we'll reopen if that's not the case.
